### ISSUE TITLE
removeQueryParams can't handle empty hash

### ISSUE THREAD

**Issue by kamholz** [BitySA/oauth2-auth-code-pkce#10]
As currently written, `removeQueryParams` messes up the URL when there is no hash portion. The `.split('#')` will make hashUrlPart undefined when there is no hash, but the code doesn't check for this and instead always returns ``${urlPart}#${hashUrlPart}``. The result is an erroneous hash of `#undefined` for such cases. Should be an easy fix.

**Comment by kamholz** [comment]
OK, I see this is already addressed by #9. Hasn't been merged yet, though?

**Comment by lf94** [comment]
Sorry for the delay. I'm pretty stretched thin as it is :slightly_smiling_face: I'll get around to this today.

**Comment by lf94** [comment]
@kamholz it'll be deployed as soon as our internal CI is done with it. Thank you :slightly_smiling_face:

**Comment by kamholz** [comment]
Thanks!!
