### ISSUE TITLE
 Unhandled promise rejection ReferenceError: 'crypto' is undefined

### ISSUE THREAD

**Issue by yu-allen** [BitySA/oauth2-auth-code-pkce#20]
In IE11, I am getting this error.

![Screen Shot 2020-11-04 at 12 19 19 PM](https://user-images.githubusercontent.com/46333061/98163688-01dc2900-1e98-11eb-96e4-428082a883c9.png)

Is there any recommended polyfill to fix this issue?

**Comment by lf94** [comment]
Hey @yu-allen , you should use a polyfill to provide this. Here it fails probably because IE11 doesn't support the SubtleCrypto interface. https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto

**Comment by yu-allen** [comment]
Awesome, thanks for the info. We ended resolving using the Crypto Shim: https://github.com/vibornoff/webcrypto-shim
