### ISSUE TITLE
Doc issues and a few cognito notes.

### ISSUE THREAD

**Issue by fimbulvetr** [BitySA/oauth2-auth-code-pkce#22]
First, thank you for this library! It is the finest I found, the code is nice, sweet and to the point. It is easy to understand and I hope it stays this way. I appreciate you only support auth_flow with PKCE on the client side. It makes it much easier to grok because the code is so targeted.

Second, I think we should update the documentation slightly - I would do a PR but I think it's so trivial you can just include it in your next update. The documentation for Usage should include a step of `npm run build` prior to instructing `npm run serve:tests`.

Also, in the tests/panel.html, the redirectUrl uses port 8000 instead of 8080.

Most importantly, for your incoming users I'd like to say that yes this does work with AWS cognito and is a sweet, sweet relief from having to use the amplify garbage and this is considerably less complex than `amazon-cognito-auth-js`. One final note, among the universe of incredibly detailed things you need to know about getting cognito working - You need to use a client id that DOES NOT have a secret. This means uncheck generate secret when you are creating the client (or GenerateSecret: false in cloudformation). Also even though AWS documentation says 

> The user pool client makes requests to this endpoint directly and not through the system browser.

This is NOT true when using Auth Flow w/ PKCE, and this library is exactly for that and will suit your needs perfectly. 

Thank you @BitySA

**Comment by lf94** [comment]
Hey @fimbulvetr !

Thank you very much for your kind words. Yes, I think this may be the nicest TypeScript I've ever written to date. I think the secret sauce is keeping the scope extremely focused. It will remain this way forever. There is no functional benefit to adding more to it; it supports the auth code PKCE flow and that's all it needs to do. If we ever get an OAuth 3 or even an OAuth 2.N, there will be a new package for every new N.

I'll update the documentation to correct the issues you brought up.

I'll add a blurb about AWS, since it seems a few others are using it for that.

**Comment by fimbulvetr** [comment]
Great. I think if you are interested in supporting the cognito crowd (there are some of us, anyway) I think mentioning it in the tags, etc would be great. The notes I mentioned above are almost enough to get started using your project on cognito, and any one reasonably versed in cognito should know the rest. They are of course welcome to message me, I was able to use this & apollo client without a single amplify dependency. So far I have a production client-side version of this working very well with svelte 3/rollup. It was a very easy setup. It's one of those packages that's _drama free_ to add and setup. IMO this is important for developers that are under a time crunch and just need something that works.

**Comment by lf94** [comment]
(The pluggable storage part probably won't be done any time soon, as localStorage works for our own systems (https://bity.com/exchange/) already.)
