### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by Tim-Erwin** [BitySA/oauth2-auth-code-pkce#23]
Recently I wanted to use this library but failed. The structure of the code made it impossible to adapt it in a way that would fit my application. So after some time of trial and error I decided to copy the library and change the code with these goals:

- break it into smaller pieces so that
  - it is easier to maintain
  - it is possible to change single aspects
- remove duplicate code
- make the process as transparent as possible with as little magic as possible
- keep the API mostly as it is
- use `async`/`await` instead of `then()`

Are you interested in integrating such changes in general into your repository? Personally I think, the library would benefit from it, but well, we all do like our own code, don't we? ;-) If so, I could make a fork and drop my code in so you can have a look. If you rather not have someone touch basically all lines of your code, well, I can make it available elsewhere 🤷

**Comment by lf94** [comment]
No thank you. The fact you were able to do all this actually gives credit toward the current structure of the project.

I don't understand how the process isn't already transparent as possible. There are zero dependencies. All the code is there in that one file!

Feel free to make it available elsewhere. :slightly_smiling_face:

**Comment by lf94** [comment]
I would like to hear what didn't work for you if you don't mind either. :slightly_smiling_face:

**Comment by Tim-Erwin** [comment]
Put simply I was not able to change the flow, connect it to my program. Everything is in long, interconnected functions which cannot be broken up. My app kept redirecting and reloading whatever I tried. It was probably my fault...

> Keep in mind this project was designed exclusively for web browsers, and not for node or things like React-Native.

Sure, PKCE was developed for browsers so that makes sense.

> I don't understand how the process isn't already transparent as possible.

As a user of the lib it's hard to see what happens and how to change it because there is lots of magic.

> No thank you.

Ok, was just an offer. Good luck! 😀👍

**Comment by lf94** [comment]
> As a user of the lib it's hard to see what happens and how to change it because there is lots of magic.

I would still greatly appreciate if you could expand on this! The whole point of the 1 file is to be easy to understand, and not have any "magic". Everything is commented quite a bit too.

> Ok, was just an offer.

Absolutely, and I really appreciate it! I don't mean the tone to be negative; I mean the "No thank you" in the nicest tone possible X)

**Comment by Tim-Erwin** [comment]
Instead of explaining, I can show you my code 😃 https://github.com/Tim-Erwin/oauth2-pkce

The functions are small and composable, the code is dry, the control flow is easy to follow.

I don't really see, how having just one file helps with understanding or even auditing. For this case, however, the npm package has a single-file version included 😄

Anyway, thanks for putting this library in the open. While I ended up making my own, I still benefited greatly!
