### ISSUE TITLE
License Q

### ISSUE THREAD

**Issue by pquerna** [BitySA/oauth2-auth-code-pkce#25]
Hello,

Thank you for writing oauth2-auth-code-pkce!  I noticed that the project is currently under an [AGPLv3 license](https://github.com/BitySA/oauth2-auth-code-pkce/blob/master/LICENSE).

I was wondering if you could consider changing the license to a more liberal MIT or Apache v2?  This would let the library be used as a library more easily in many projects.

If not, no problem, licensing is obviously your choice.

Thanks!

Paul

**Comment by lf94** [comment]
I'll have to ask Bity. :slightly_smiling_face:

**Comment by lf94** [comment]
@pquerna we will move it to Apache 2.

**Comment by lf94** [comment]
@pquerna we have moved it, sorry for the long delay! 2.13.0 and above is now Apache 2.

**Comment by pquerna** [comment]
Great! Thank you again for this great little library!
