### ISSUE TITLE
Add a "repository" key to the package.json file

### ISSUE THREAD

**Issue by Windvis** [BitySA/oauth2-auth-code-pkce#3]
I found this client by searching npmjs.com. I noticed the link to the repository was missing which made this github page hard to find (it's not indexed on search engines yet). Adding a "repository" field to the package.json file _should_ add that link to the Github repository.

**Comment by lf94** [comment]
Ah good catch. This repository is actually being mirrored from our GitLab, so it never occurred to me to link it here. I'll add it manually - thank you!
