### ISSUE TITLE
API to clear state?

### ISSUE THREAD

**Issue by ispyinternet** [BitySA/oauth2-auth-code-pkce#6]
Should this library expose a logout / or reset state API?

**Comment by lf94** [comment]
It probably should. I thought that it was unnecessary because all that's needed to clear state, is to clear `oauth2authcodepkce-state` property in `localstorage`.

In the next release I'll add `.destroyState()`, which should do as the name implies :)

**Comment by lf94** [comment]
I called it `reset()` instead. It's published in 2.7.1.
